# Generated by Django 5.1.4 on 2025-08-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartdriverapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Name',
            new_name='name',
        ),
    ]
