# Generated by Django 5.1.4 on 2025-08-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdriverapp', '0002_rename_email_register_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
