# Generated by Django 5.1.4 on 2025-08-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdriverapp', '0003_register_age_register_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='state',
            field=models.CharField(blank=True, choices=[('KL', 'kerala'), ('KA', 'karnataka'), ('TN', 'tamilnadu'), ('O', 'other')], max_length=2, null=True),
        ),
    ]
