# Generated by Django 5.1.4 on 2025-09-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdriverapp', '0006_alter_register_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='state',
            field=models.CharField(blank=True, choices=[('K', 'kerala'), ('KA', 'karnataka'), ('T', 'tamilnadu'), ('O', 'other')], max_length=2, null=True),
        ),
    ]
