# Generated by Django 5.1.7 on 2025-09-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdriverapp', '0007_alter_register_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='licenceno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
