# Generated by Django 5.1.4 on 2025-10-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdriverapp', '0009_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_number',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='v_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
