# Generated by Django 5.1.4 on 2025-10-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdriverapp', '0010_remove_vehicle_vehicle_number_vehicle_v_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
