# Generated by Django 5.1.4 on 2025-10-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartdriverapp', '0011_vehicle_vehicle_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='v_type',
            new_name='vehicle_type',
        ),
    ]
