# Generated by Django 5.1.4 on 2025-10-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdriverapp', '0012_rename_v_type_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='driver_photos/')),
                ('license_number', models.CharField(max_length=50)),
                ('assigned_vehicle', models.CharField(max_length=50)),
            ],
        ),
    ]
