# Generated by Django 5.2.5 on 2025-10-06 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartdriverapp', '0014_remove_driver_assigned_vehicle_driver_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_model',
        ),
    ]
