# Generated by Django 5.2.5 on 2025-10-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdriverapp', '0015_remove_vehicle_vehicle_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
