# Generated by Django 5.2.8 on 2025-11-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdriverapp', '0016_alter_vehicle_vehicle_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('uploaded_documents', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
    ]
